#!/usr/bin/env python3
"""Paper A -- appendix table: clean-data test performance, BVU vs the
parameter-matched MLP, all seven Phase-1 datasets at 25% and 100% of the
training data.

Reads only the frozen processed Phase-1 exports (never raw/history files) and
writes `clean_performance.tex` + `clean_performance_data.csv` next to this
script. Nothing is trained and no result file is modified.

Conventions match `paper/figures/supplementary/make_figS1_clean_benchmarks.py`:
`headline_value` (test accuracy or test R^2), BVU and `mlp_matched`
paired by seed, mean +/- sample-SD (ddof=1) over seeds.

Usage:
    python paper/tables/make_clean_performance_table.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_FIGURES = _HERE.parent / "figures"
if str(_FIGURES) not in sys.path:
    sys.path.insert(0, str(_FIGURES))

from lib import data as D  # noqa: E402

PROCESSED = D.PAPER_A / "results" / "processed"
MLP_SOURCES = (
    "phase1_runs_small.json",
    "phase1_runs_mid.json",
    "phase1_runs_mnist_0.25.json",
    "phase1_runs_mnist_1.0.json",
    "phase1_runs_fashion_mnist_0.25.json",
    "phase1_runs_fashion_mnist_1.0.json",
)
FRACTIONS = (0.25, 1.0)
DATASET_LABEL = {
    "breast_cancer": "Breast Cancer",
    "wine": "Wine",
    "digits": "Digits",
    "diabetes": "Diabetes",
    "california_housing": "California Housing",
    "mnist": "MNIST",
    "fashion_mnist": "Fashion-MNIST",
}
METRIC_LABEL = {"accuracy": "Accuracy", "r2": r"$R^2$"}


def _key(r: dict) -> tuple:
    return (r["dataset"], r["train_fraction"], r["family"], r["seed"])


def load_rows() -> tuple[list[dict], list[dict]]:
    v03 = D.load_phase1_cellv03_runs()
    mlp: list[dict] = []
    for name in MLP_SOURCES:
        rows = D.load_json(PROCESSED / name)
        mlp.extend(r for r in rows if r["family"] == "mlp_matched")
    D.assert_unique_keys(mlp, _key, "phase1 mlp_matched sources (combined)")
    return v03, mlp


def build_records() -> list[dict]:
    v03, mlp = load_rows()
    v03_idx = {_key(r): r for r in v03}
    mlp_idx = {_key(r): r for r in mlp}
    out = []
    for ds in D.PHASE1_CLEAN_DATASETS:
        for frac in FRACTIONS:
            seeds = sorted(
                s for (d, f, fam, s) in v03_idx
                if d == ds and abs(f - frac) < 1e-9 and fam == "cellv0.3"
            )
            if len(seeds) != D.EXPECTED_N_SEEDS:
                raise ValueError(f"{ds} @ {frac}: BVU seeds {seeds}")
            a_rows = [v03_idx[(ds, frac, "cellv0.3", s)] for s in seeds]
            b_rows = [mlp_idx[(ds, frac, "mlp_matched", s)] for s in seeds]
            metrics = {r["headline_metric"] for r in a_rows + b_rows}
            if len(metrics) != 1:
                raise ValueError(f"{ds} @ {frac}: mixed headline metrics {metrics}")
            a = [r["headline_value"] for r in a_rows]
            b = [r["headline_value"] for r in b_rows]
            am, asd, _ = D.mean_std(a)
            bm, bsd, _ = D.mean_std(b)
            dm, dsd, n = D.mean_std([x - y for x, y in zip(a, b)])
            out.append({
                "dataset": ds, "train_fraction": frac, "metric": metrics.pop(),
                "bvu_mean": am, "bvu_std": asd,
                "mlp_mean": bm, "mlp_std": bsd,
                "delta_mean": dm, "delta_std": dsd, "n_seeds": n,
            })
    return out


def _num(x: float, signed: bool = False) -> str:
    s = f"{x:.3f}"
    if float(s) == 0.0:
        s = "0.000"
    elif signed and x > 0:
        s = "+" + s
    return s


def _cell(mean: float, sd: float, signed: bool = False) -> str:
    return f"${_num(mean, signed)} \\pm {sd:.3f}$"


def render_tex(records: list[dict]) -> str:
    lines = [
        "% Clean-data test performance, generated by make_clean_performance_table.py.",
        "% Import with: \\input{tables/clean_performance}",
        "\\begingroup",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\renewcommand{\\arraystretch}{1.12}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Clean-data test performance of BVU and its parameter-matched MLP "
        "on the seven benchmark datasets at 25\\% and 100\\% of the training data "
        "(mean $\\pm$ sample SD over seeds 0, 1, 2). "
        "$\\Delta$ is BVU $-$ matched MLP, computed per seed and then averaged; "
        "higher is better for both accuracy and $R^2$.}",
        "\\label{tab:clean_performance}",
        "\\begin{tabular}{@{}p{0.22\\linewidth}p{0.09\\linewidth}p{0.10\\linewidth}"
        "p{0.16\\linewidth}p{0.16\\linewidth}p{0.16\\linewidth}@{}}",
        "\\toprule",
        "Dataset & Train fraction & Metric & BVU & Matched MLP & $\\Delta$ \\\\",
        "\\midrule",
    ]
    for i, ds in enumerate(D.PHASE1_CLEAN_DATASETS):
        if i:
            lines.append("\\addlinespace[2pt]")
        for j, frac in enumerate(FRACTIONS):
            r = next(x for x in records
                     if x["dataset"] == ds and abs(x["train_fraction"] - frac) < 1e-9)
            name = DATASET_LABEL[ds] if j == 0 else ""
            lines.append(
                f"{name} & {int(round(frac * 100))}\\% & {METRIC_LABEL[r['metric']]} & "
                f"{_cell(r['bvu_mean'], r['bvu_std'])} & "
                f"{_cell(r['mlp_mean'], r['mlp_std'])} & "
                f"{_cell(r['delta_mean'], r['delta_std'], signed=True)} \\\\"
            )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\parbox{0.98\\linewidth}{\\footnotesize Values are test-set accuracy "
        "(classification) or $R^2$ (regression) at the checkpoint selected on validation "
        "data. Both models use the parameter budgets and optimization settings in the "
        "reproducibility tables. No significance testing is applied ($n=3$ seeds).}",
        "\\end{table}",
        "\\endgroup",
        "",
    ]
    return "\n".join(lines)


def write_csv(records: list[dict], path: Path) -> None:
    fields = ["dataset", "train_fraction", "metric", "bvu_mean", "bvu_std",
              "mlp_mean", "mlp_std", "delta_mean", "delta_std", "n_seeds"]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(records)


def main() -> None:
    records = build_records()
    tex_path = _HERE / "clean_performance.tex"
    csv_path = _HERE / "clean_performance_data.csv"
    tex_path.write_text(render_tex(records))
    write_csv(records, csv_path)
    for r in records:
        print(
            f"{r['dataset']:<19} {r['train_fraction']:<5} {r['metric']:<8} "
            f"v03={r['bvu_mean']:.4f}±{r['bvu_std']:.4f}  "
            f"mlp={r['mlp_mean']:.4f}±{r['mlp_std']:.4f}  "
            f"d={r['delta_mean']:+.4f}±{r['delta_std']:.4f}"
        )
    print(f"Wrote {tex_path.relative_to(D.REPO_ROOT)}")
    print(f"Wrote {csv_path.relative_to(D.REPO_ROOT)}")


if __name__ == "__main__":
    main()
